ALTER TABLE REFERENCE ADD PRIMARY KEY (id);

ALTER TABLE CHROMOSOME ADD PRIMARY KEY (id);
ALTER TABLE CHROMOSOME ADD FOREIGN KEY (reference_id) REFERENCES REFERENCE (id);

ALTER TABLE BIOLOGIC_ANNOTATION ADD PRIMARY KEY (id);

ALTER TABLE POPULATION ADD PRIMARY KEY (id);

ALTER TABLE VARIATION ADD PRIMARY KEY (id);
ALTER TABLE VARIATION ADD FOREIGN KEY (population_id) REFERENCES POPULATION (id);

ALTER TABLE CHROMOSOME_VARIATION_ANNOTATION ADD PRIMARY KEY (id);
ALTER TABLE CHROMOSOME_VARIATION_ANNOTATION ADD FOREIGN KEY (chromosome_id) REFERENCES CHROMOSOME (id);
ALTER TABLE CHROMOSOME_VARIATION_ANNOTATION ADD FOREIGN KEY (biologic_annotation_id) REFERENCES BIOLOGIC_ANNOTATION (id);
ALTER TABLE CHROMOSOME_VARIATION_ANNOTATION ADD FOREIGN KEY (variation_id) REFERENCES VARIATION (id);

ALTER TABLE INDIVIDUAL ADD PRIMARY KEY (id);
ALTER TABLE INDIVIDUAL ADD FOREIGN KEY (population_id) REFERENCES POPULATION (id);
